# Generated by Django 6.0.3 on 2026-04-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_onboarding_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plan_status',
            field=models.CharField(choices=[('active', 'Ativo'), ('cancelled', 'Cancelado'), ('suspended', 'Suspenso')], default='active', max_length=20),
        ),
    ]
