# Generated by Django 6.0.3 on 2026-04-18 14:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_store_address_store_cnpj_store_phone_user_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('subscription_id', models.CharField(max_length=255)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='abacatepay_subscription_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='user',
            name='plan_status',
        ),
        migrations.RemoveField(
            model_name='user',
            name='trial_ends_at',
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(max_length=255, unique=True, verbose_name='ID Assinatura (AbacatePay)')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('expired', 'Expirada'), ('cancelled', 'Cancelada'), ('pending', 'Pendente')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=49.9, max_digits=10)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('billing_cycle', models.CharField(default='monthly', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateTimeField()),
                ('next_billing_date', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(default='abacatepay', max_length=50)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
