# Generated by Django 6.0.3 on 2026-04-07 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='date',
        ),
        migrations.AlterField(
            model_name='category',
            name='account_type',
            field=models.CharField(choices=[('PF', 'PF'), ('PJ', 'PJ'), ('both', 'Ambas')], max_length=4),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saída')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='financial.customer', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='first_due_date',
            field=models.DateField(verbose_name='Data da Primeira Parcela'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='installments_count',
            field=models.IntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao_debito', 'Cartão no Débito'), ('cartao_credito', 'Cartão no Crédito'), ('check', 'Cheque'), ('promissory', 'Promissória'), ('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária'), ('installment', 'Parcelamento')], max_length=20, verbose_name='Tipo de Pagamento'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateField(verbose_name='Data da Venda'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('partial', 'Parcial'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='saleinstallment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('overdue', 'Atrasado')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('cartao_debito', 'Cartão no Débito'), ('cartao_credito', 'Cartão no Crédito'), ('check', 'Cheque'), ('promissory', 'Promissória'), ('boleto', 'Boleto'), ('transferencia', 'Transferência Bancária'), ('installment', 'Parcelamento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Entrada'), ('expense', 'Saída'), ('transfer', 'Transferência')], max_length=10, verbose_name='Tipo'),
        ),
    ]
