# Generated by Django 6.0.3 on 2026-04-07 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_remove_transfer_date_alter_category_account_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('PF', 'PF'), ('PJ', 'PJ')], default='PJ', max_length=2),
        ),
        migrations.AddField(
            model_name='sale',
            name='account_type',
            field=models.CharField(choices=[('PF', 'PF'), ('PJ', 'PJ')], default='PJ', max_length=2),
        ),
    ]
